# https://cloud.google.com/appengine/docs/standard/go113/config/appref
runtime: go113

handlers:
- url: /.*
  script: auto

# env_variables:
#  PORT: '8080'
#  GOOGLE_APPLICATION_CREDENTIALS: '/Users/peterplamondon/oldmancodes-224604-2f9d9c625b1b.json'
