# https://cloud.google.com/appengine/docs/standard/go113/config/appref
runtime: go113
service: transcription-gcp

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

env_variables:
  PROJECT_ID: elated-practice-224603
  STORAGE_LOCATION: us-west2
  STATIC_FILES_BUCKET: elated-practice-224603
  ENCRYPTED_BUCKET: elated-practice-224603-lead-expert-secret
  CONFIG_FILE: config.yaml
  KMS_LOCATION: us-west2
  KMS_KEYRING: devkeyring
  KMS_KEY: config
  TASKS_LOCATION: "us-west2"
  TASK_TRANSCRIPTION_GCP_SERVICENAME: "transcription-gcp"
  TASK_TRANSCRIPTION_GCP_WRITE_TO_Q: "TranscriptionComplete"
  TASK_TRANSCRIPTION_GCP_SVC_TO_HANDLE_REQ: "transcription-complete"
  TASK_TRANSCRIPTION_GCP_PORT: 8083