# https://cloud.google.com/appengine/docs/standard/go113/config/appref
runtime: go113
service: transcription-complete

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

env_variables:
  PROJECT_ID: elated-practice-224603
  STORAGE_LOCATION: us-west2
  ENCRYPTED_BUCKET: elated-practice-224603-lead-expert-secret
  CONFIG_FILE: config.yaml
  KMS_LOCATION: us-west2
  KMS_KEYRING: devkeyring
  KMS_KEY: config
  TASKS_LOCATION: "us-west2"
  TASK_TRANSCRIPTION_COMPLETE_SERVICENAME: "transcription-complete"
  TASK_TRANSCRIPTION_COMPLETE_WRITE_TO_Q: "TranscriptQA"
  TASK_TRANSCRIPTION_COMPLETE_SVC_TO_HANDLE_REQ: "transcript-qa"
  TASK_TRANSCRIPTION_COMPLETE_PORT: 8084