# https://cloud.google.com/appengine/docs/standard/go113/config/appref
runtime: go113
service: initial-request

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

env_variables:
  PROJECT_ID: elated-practice-224603
  STORAGE_LOCATION: us-west2
  ENCRYPTED_BUCKET: elated-practice-224603-lead-expert-secret
  CONFIG_FILE: config.yaml
  KMS_LOCATION: us-west2
  KMS_KEYRING: devkeyring
  KMS_KEY: config
  TASKS_LOCATION: "us-west2"
  TASK_INITIAL_REQUEST_SERVICENAME: "initial-request"
  TASK_INITIAL_REQUEST_WRITE_TO_Q: "ServiceDispatch"
  TASK_INITIAL_REQUEST_SVC_TO_HANDLE_REQ: "service-dispatch"
  TASK_INITIAL_REQUEST_PORT: 8081