# https://cloud.google.com/appengine/docs/standard/go113/config/appref
runtime: go113
service: default

handlers:
- url: /static
  static_dir: public

- url: /(.*\.(gif|png|jpg|ico))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg|ico)$

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

env_variables:
  PROJECT_ID: elated-practice-224603
  STORAGE_LOCATION: us-west2
  STATIC_FILES_BUCKET: elated-practice-224603
  ENCRYPTED_BUCKET: elated-practice-224603-gowebapp-secret
  CONFIG_FILE: config.yaml
  KMS_LOCATION: us-west2
  KMS_KEYRING: devkeyring
  KMS_KEY: config
  TASKS_LOCATION: "us-west2"
  TASK_DEFAULT_SVC: "default"
  TASK_DEFAULT_WRITE_TO_Q: "InitialRequest"
  TASK_DEFAULT_PORT: 8080
  